name: tawakkul
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  geocoding: ^2.1.1
  flutter_compass: ^0.8.1
  adhan: ^2.0.0  # Reverted to last known stable version
  geolocator: ^9.0.0
  intl: ^0.18.0
  quran: ^1.0.0
  shared_preferences: ^2.0.0
  hijri: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/home_icon.png
    - assets/images/mosque_icon.png
    - assets/images/kaaba_icon.png